### ISSUE TITLE
EL PASSO?

### ISSUE THREAD

**Issue by jedisct1** [tokenzoo/tokenzoo.github.io#7]
Hi,

And congrats for setting up that amazing knowledge base on anonymous credentials schemes!

Do you think [EL PASSO](https://arxiv.org/pdf/2002.10289.pdf) could possibly be considered for inclusion?

Thanks!

-Frank.

**Comment by asn-d6** [comment]
Yep, I think that's definitely in-scope. I can try to add it at some point this week, or feel free to do a PR yourself!

Thanks a lot!

**Comment by asn-d6** [comment]
Hey, I added info for EL PASSO in https://github.com/tokenzoo/tokenzoo.github.io/commit/f8ab2b29f18bb9292beebe3e3888fe907350388e .

I didn't manage to extract the right performance figures from the paper -- that is, separate "prover time" from "verifier time" so the performance figures are incomplete.

If you feel like adding more info for the paper, just submit a PR.

Thanks a lot!
